### PR TITLE
feature(haswstab2): created numbering 1st, 2nd , ... for HAWCStab2 mo…

### PR DESCRIPTION
**Pull request by RiekeJ**
At least numbering of modes is introduced. not really realized a classification.

### CODE REVIEW

**Comment by RiekeJ** [comment]
merged xarray update into this branch already.

**Review by hendrikverdonck — COMMENTED** [review]
How consistent are the first three HS2 modes lag, SS, FA? I think it is risky to just overwrite the mode names.

**Comment by RiekeJ** [comment]
All my HS2 results show the first mode as lag mode with 2.15 and 2.16 HS releases. The first tower modes are very likely the second and third mode. Maybe best solution would be to put that into the Qsettings section, so that users can change the default?

**Comment by RiekeJ** [comment]
Pushed just now the extensions.

**Review by hendrikverdonck — APPROVED** [review]
Works great

**Comment by hendrikverdonck** [comment]
Our testing pipeline showed that something is broken for python 3.9 versions (https://github.com/DLR-AE/CampbellViewer/actions/runs/12049528910/job/33597149253). Python >=3.10 still works fine

**Comment by RiekeJ** [comment]
OK, a from future is needed there to fix it. The pipe | symbol (== or) in type hints is not part of standard Python 3.9.

**Pull request merged**
